### ISSUE TITLE
JQuery content pagination broken

### ISSUE THREAD

**Issue by cytadela8** [warsztatywww/aplikacjawww#118]
On profile page we use JQuery content pagination to create 4 tabs. This is broken. (Tabs are not displayed at all and all content is concatenated)

**Comment by cytadela8** [comment]
@krzys-h This maybe related to #111

**Comment by krzys-h** [comment]
According to bisect, `4e0464e0657f2b45c2486ff25e5825d160305e28 is the first bad commit`, which is this:
```
commit 4e0464e0657f2b45c2486ff25e5825d160305e28
Merge: 92b64e0 7bb536a
Author: Artur Puzio <contact@puzio.waw.pl>
Date:   Tue Mar 3 23:49:17 2020 +0000

    Merge pull request #92 from warsztatywww/editor
    
    Improved text editor

diff --cc templates/profile.html
index af0140e,d29b6b3..19b35e0
--- a/templates/profile.html
+++ b/templates/profile.html
@@@ -207,10 -172,12 +207,14 @@@
  {% endblock %}
  
  {% block script %}
+   {{ block.super }}
+   {{ user_profile_page_form.media }}
+   {{ user_cover_letter_form.media }}
+ 
    <script>
      $(document).ready(function() {
 +      $('[data-toggle="tooltip"]').tooltip({html: true});
 +
        paginate_content("pagination_content");
  
        if(["#data", "#profile_page", "#cover_letter", "#user_info"].indexOf(location.hash) != -1) {

```

The call to .tooltip() throws an error, preventing paginate_content from being called (and, I just noticed, tooltip became part of Bootstrap only on Bootstrap 4, for Bootstrap 3 this worked because of... jQuery UI which I removed :joy: - but this does not seem to be the problem as restoring jQuery UI does not fix it)

**Comment by krzys-h** [comment]
Actually, `.tooltip` seems to be working without jQuery UI, everything was just totally broken because of jQuery loading order
